server:
  port: 8085
spring:
  application:
    name: selmag-admin-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: hNl7X5b3qO9mlNqY9L9W2GLZ7iBISjlv
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: hNl7X5b3qO9mlNqY9L9W2GLZ7iBISjlv
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: hNl7X5b3qO9mlNqY9L9W2GLZ7iBISjlv
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
    register-with-eureka: false