selmag:
  services:
    catalogue:
      uri: http://172.17.0.1:8081
      registration-id: keycloak
spring:
  application:
    name: selmag-manager-app
  datasource:
    url: jdbc:postgresql://172.17.0.1:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 59kbFm41NnKeSJmyf1UDJwShPJnehGJs
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
