server:
  port: 8888
spring:
  application:
    name: selmag-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/protsenkopavel/sc24-config.git
          clone-on-start: true
          default-label: main
          search-paths:
            - '{application}/{profile}'